name: 🛠️ Branch Checkup
on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkup:
    name: 👮‍♂️ Typecheck, Healthcheck, Lint and Format
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup Repo
        uses: actions/checkout@v4

      - name: 🏗 Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 🏗 Get PNPM store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: 🏗 Setup PNPM cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: "📦 Cache Node Modules"
        uses: actions/cache@v4.1.1
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: 📦 Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm install

      - name: 👨‍⚕️ Expo Doctor
        run: pnpm run doctor

      - name: 🏗 Setup Turborepo Cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: 🧹 Dedupe
        run: pnpm dedupe --check

      - name: 🧪 Typecheck
        run: pnpm run typecheck

      - name: 🧹 Lint
        run: pnpm run lint

      - name: 💅 Format
        run: pnpm run format
